# Setup
title:               Algoritmi
tagline:             'Algoritmi 120'
description:         'Laboratorijske vježbe iz algoritama'
url:                 https://marinmaslov.github.io/algo.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Marin Maslov
  url:               ''
  email:             ''

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
